name: Run Tests

# Define as permissões necessárias para este workflow
permissions:
  contents: write  # Permite operações de escrita

# Define os eventos que acionam o workflow
on:
  push:
    branches:
      - main  # Aciona para a branch 'main'

jobs:
  test:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Install packages
        run: |
          npm install
      - name: Start server and run tests
        run: |
          npm start & npx wait-on http://localhost:3000
          npm test
          
      - name: Archive Test Report
        uses: actions/upload-artifact@v4  # Certifique-se de usar a versão correta
        with:
          name: test-report
          path: report/  # Arquivo de cobertura gerado pelo Jest
  
      - name: Create 'docs' Directory
        run: mkdir -p docs  # Cria a pasta 'docs' se não existir
  
      - name: Create .nojekyll File
        run: touch docs/.nojekyll
  
      - name: Copy Report to 'docs'
        run: cp -r coverage/* docs/  # Copia o conteúdo para 'docs'
  
      - name: Create '.nojekyll' File
        run: touch docs/.nojekyll  # Desativa o Jekyll para evitar problemas de conversão
  
      - name: Publish test coverage report
        uses: EndBug/add-and-commit@v4
        with:
          add: docs
          force: true
          message: "Add generated docs"  # Mensagem para o commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Para autenticação no GitH
