
name: TDC Floripa
on: [push]

jobs:
  k6_local_test:
    name: Load API Test with K6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run k6 script by bash file
        run: bash __test__/tdcTest.sh

      - name: Upload folder performance test reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: results/